#!/usr/bin/env node
/**
 * Generate src/content/promises.generated.ts from the corpus.
 *
 * Reads every `corpus/<start>-<end> <name>/promises.yaml`, pulls the four
 * top-level fields the app needs from each promise (id, theme, restatement,
 * measurable), and emits a typed, committed data module. The full four-
 * dimension scoring stays in the corpus; this is the curated projection the
 * chart consumes, exactly the same split the deficit topic uses for its series.
 *
 * Dependency-free by design: corpus fields are single-line and indented at a
 * fixed depth (promise item at 2 spaces, its fields at 4, folded quote bodies
 * at 6), so a small indentation-aware scanner is enough — no YAML parser, no
 * install, no network. Re-run after editing the corpus:  npm run build:corpus
 */
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');
const CORPUS = join(ROOT, 'corpus');
const OUT = join(ROOT, 'src', 'content', 'promises.generated.ts');

const QUALITIES = ['full', 'partial', 'no'];
const unquote = (s) => s.replace(/^["'](.*)["']$/, '$1');

function parsePromises(yamlText) {
  const out = [];
  let cur = null;
  for (const line of yamlText.split(/\r?\n/)) {
    const start = line.match(/^ {2}- id:\s*(.+?)\s*$/);
    if (start) {
      if (cur) out.push(cur);
      cur = { id: unquote(start[1]) };
      continue;
    }
    if (!cur) continue;
    // exactly-4-space field lines only — disqualifies 6-space quote/sub-block lines
    const field = line.match(/^ {4}(theme|restatement|measurable):\s*(.+?)\s*$/);
    if (field) cur[field[1]] = unquote(field[2]);
  }
  if (cur) out.push(cur);
  return out;
}

const terms = [];
for (const name of readdirSync(CORPUS)) {
  const dir = join(CORPUS, name);
  if (!statSync(dir).isDirectory()) continue;
  const m = name.match(/^(\d{4})-(\d{4}) (.+)$/);
  if (!m) continue;
  const [, fromStr, toStr, surname] = m;
  const files = readdirSync(dir);
  const promisesFile = files.find((f) => f === 'promises.yaml');
  const speechFile = files.find((f) => /^\d{4}-acceptance\.md$/.test(f));
  if (!promisesFile) continue;
  const speechYear = speechFile ? Number(speechFile.slice(0, 4)) : null;
  const promises = parsePromises(readFileSync(join(dir, promisesFile), 'utf8')).map((p) => {
    if (!QUALITIES.includes(p.measurable)) {
      throw new Error(`${name}/${p.id}: bad measurable ${JSON.stringify(p.measurable)}`);
    }
    return { id: p.id, theme: p.theme ?? 'other', restatement: p.restatement ?? p.id, quality: p.measurable };
  });
  terms.push({
    key: name,
    surname,
    from: Number(fromStr),
    to: Number(toStr),
    termLabel: `${fromStr}–${toStr}`,
    speechYear,
    label: speechYear ? `${surname} ${speechYear}` : surname,
    promises,
  });
}

terms.sort((a, b) => a.from - b.from || (a.speechYear ?? 0) - (b.speechYear ?? 0));

const total = terms.reduce((n, t) => n + t.promises.length, 0);
const banner =
  '// AUTO-GENERATED by scripts/build-corpus.mjs from corpus/*/promises.yaml.\n' +
  '// Do not edit by hand — edit the corpus and run `npm run build:corpus`.\n';

const body = `${banner}
export type Quality = 'full' | 'partial' | 'no';

export interface CorpusPromise {
  id: string;
  theme: string;
  restatement: string;
  quality: Quality;
}

export interface CorpusTerm {
  /** Corpus directory name, e.g. "2009-2013 Obama". Stable key. */
  key: string;
  surname: string;
  /** Inauguration year that opened the term. */
  from: number;
  /** Next inauguration year. */
  to: number;
  /** "2009–2013" — display label for the term span. */
  termLabel: string;
  /** Election/acceptance-speech year the promises were made. */
  speechYear: number | null;
  /** Short bar label, e.g. "Obama 2008". */
  label: string;
  promises: CorpusPromise[];
}

/** Every term with an extracted promise set, oldest first. */
export const CORPUS_TERMS: CorpusTerm[] = ${JSON.stringify(terms, null, 2)};

/** Total promises across the corpus (sanity anchor for tests). */
export const CORPUS_PROMISE_COUNT = ${total};
`;

writeFileSync(OUT, body);
console.log(
  `wrote ${OUT}\n  ${terms.length} terms, ${total} promises ` +
    `(${terms.map((t) => `${t.label}:${t.promises.length}`).join(', ')})`,
);
